#!/bin/bash




if [ $EUID != 0 ]; then
	gksu "$0" "$@"
	exit $?
fi

###### fix this to point to the install directory
cd "$PROGRAM_DIR"

touch "$PID_FILE"

./rfid_reader &
echo "$!" > "$PID_FILE"
sleep 2
java ReaderClass &
echo "$!" > "$PID_FILE"
