#!/bin/bash

PID_FILE=/var/run/fridgePIDS.pid
PROGRAM_DIR=/usr/bin/FridgeController
DESC="Service control script for fridgeController"
NAME=fridgeControl

do_start()
{
	echo "Starting fridge controller"
	"$PROGRAM_DIR/fridgeControllerStart"
}

do_stop()
{
	echo "Stopping fridge controller"
	kill $(<$PID_FILE)
}

show_status()
{
	echo "status"
}

if [ $EUID != 0 ]; then
	gksu "$0" "$@"
	exit $?
fi

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	status)
		show_status
		;;
esac

exit 0
