#!/bin/bash

if [ $EUID != 0 ]; then
	gksu "$0" "$@"
	exit $?
fi

PROGRAM_DIR="/usr/bin/FridgeController"

mkdir "$PROGRAM_DIR"

sed -i "3iPROGRAM_DIR=$PROGRAM_DIR" fridgeControllerStart #will write to the startup script so we have the right directory

chmod +x fridgeControllerStart
chmod +x fridgeController

cp *.class rfid_reader README.md fridgeControllerStart "$PROGRAM_DIR/"

cp fridgeController /etc/init.d/

systemctl daemon-reload #reload the daemons
