#!/bin/bash

PROGRAM_DIR=/usr/bin/FridgeController
PROGRAM_DIR=/usr/bin/FridgeController
/usr/bin/FridgeController



if [ $EUID != 0 ]; then
	gksu "$0" "$@"
	exit $?
fi

###### fix this to point to the install directory
cd "$PROGRAM_DIR"

./rfid_reader &
java ReaderClass